module.exports = {
    dsa: [
        "LinearSearchList",
        "MazeSolver",
        "BinarySearchList",
        "TwoCrystalBalls",
        // "BubbleSort",
        // "QuickSort",
        // "DijkstraList",
        "InsertionSort",
        // "BTBFS",
        // "DFSOnBST",
        // "BTPreOrder",
        // "BTInOrder",
        // "BTPostOrder",
        // "CompareBinaryTrees",
        // "BFSGraphMatrix",
        // "DFSGraphList",
        // "Trie",
        // "ArrayList",
        // "SinglyLinkedList",
        // "DoublyLinkedList",
        "Queue",
        "Stack",
        // "Map",
        // "MinHeap",
        // "LRU",
    ],
}

