module.exports = {
    dsa: [
        "LRU",
        // "LinearSearchList",
        // "BinarySearchList",
        // "TwoCrystalBalls",
        // "BubbleSort",
        // "SinglyLinkedList",
        // "DoublyLinkedList",
        // "Queue",
        // "Stack",
        // "ArrayList",
        // "MazeSolver",
        // "QuickSort",
        "BTPreOrder",
        "BTInOrder",
        "BTPostOrder",
        "BTBFS",
        "DFSOnBST",
        // "CompareBinaryTrees",
        // "DFSOnBST",
        // "DFSGraphList",
        // "Trie",
        // "BFSGraphMatrix",
        // "Map",
        // "MinHeap",
        // "DijkstraList",
    ],
}

